import { Project } from '../../types/Project'

export const PROJECTS: Project[] = [
   {
      company: `GrandSchool`,
      link: 'https://grandschool.app/',
      image: '/projects/grand.png',
      badges: [
         'Js',
         'HTML5',
         'CSS',
         'Sass',
         'Scss',
         'Vite',
         'Figma',
         'Git',
         'NPM',
         'JavaScript',
         'Observer',
         'Postcss',
      ],
      title: `GrandSchool`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `GrandSchool is an educational platform for older adults,
designed to help them stay safe, confident, and informed online.`,
   },
   {
      company: `Positivus`,
      link: 'https://alexfrxx.github.io/Positivus-LandingPage/',
      image: '/projects/positivus.png',
      badges: [
         'Js',
         'HTML5',
         'SCSS',
         'Sass',
         'Webpack',
         'Figma',
         'Observer',
         'Animations',
         'Git',
         'NPM',
      ],
      title: `Positivus`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Digital Marketing Agency Landing Page Positivus`,
   },
   {
      company: `Vlad Pavlov Brand-Manager`,
      link: 'https://pavlovbrand.com',
      image: '/projects/pavlov.png',
      badges: [
         'Gulp',
         'HTML5',
         'Sass',
         'Less',
         'CSS3',
         'Observer',
         'Animations',
         'Git',
         'NPM',
      ],
      title: `Vlad Pavlov`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `This project is a personal / professional website for a Brand Manager,
designed to present expertise, experience, and personal brand in a clear and modern way.`,
   },
   {
      company: `Marketing-Pro`,
      link: 'https://alexfrxx.github.io/MarketingPro/',
      image: '/projects/marketing.png',
      badges: ['Js', 'CSS3', 'HTML5', 'Flexbox', 'Git', 'Animations'],
      title: `Marketing-Pro`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Responsive marketing landing page template with modern UI, animations & customizable layout.`,
   },
   {
      company: `GrandSchool`,
      link: 'ttps://alexfrxx.github.io/GrandSchool-CommingSoonPage/',
      image: '/projects/grand.png',
      badges: [
         'Js',
         'HTML5',
         'CSS3',
         'Figma',
         'JavaScript',
         'Animations',
         'Git',
         'NPM',
      ],
      title: `GrandSchool-Comming Soon Page`,
      logo: undefined,
      start: undefined,
      end: undefined,
      description: `Comming-soon page for GrandSchool.`,
   },
   // 15 - 30

   // 30 - 45

   // {
   //    company: ``,
   //    link: '',
   //    badges: [''],
   //    title: ``,
   //    logo: undefined,
   //    start: undefined,
   //    end: undefined,
   //    description: ``,
   // },
]
